#!/usr/bin/env python3
"""
Daily Iceberg-CPP Module Analysis
Runs one module analysis per day via claude -p (non-interactive).
Invoked by launchd: ~/Library/LaunchAgents/com.iceberg-cpp.daily-analysis.plist
"""

import subprocess
import sys
import os
import json
import shutil
from datetime import datetime, timezone, timedelta
from pathlib import Path

# ---- Config ----------------------------------------------------------------
HOME = Path(os.environ.get("HOME", Path.home()))
SCRIPT_DIR = HOME / "Code" / "iceberg-cpp-issues"
PROJECT_DIR = HOME / "Code" / "iceberg-cpp"
PROMPT_FILE = SCRIPT_DIR / "analysis_prompt.md"
LOG_DIR = SCRIPT_DIR / "logs"

# Node / claude path — keep in sync with your nvm install
NODE_BIN_DIR = HOME / ".nvm" / "versions" / "node" / "v25.8.2" / "bin"

REPORT_DIR = SCRIPT_DIR / "daily_reports"
STATE_FILE = SCRIPT_DIR / "daily_analysis_state.json"

# ---- Helpers ---------------------------------------------------------------
def _sh_run(cmd: list) -> str:
    """Run a quick shell command and return stripped stdout, or 'ERROR' on failure."""
    try:
        return subprocess.check_output(cmd, text=True, timeout=10).strip()
    except Exception:
        return "ERROR"


def _now_str(tz: timezone) -> str:
    return datetime.now(tz).isoformat()


def _today_str(tz: timezone) -> str:
    return datetime.now(tz).strftime("%Y-%m-%d")


def _find_report(tz: timezone) -> Path | None:
    """Locate the report file generated by today's analysis.

    Derives the expected filename from ``daily_analysis_state.json`` (module
    name + today's date).  Falls back to the newest ``.md`` in REPORT_DIR.
    """
    today = _today_str(tz)

    # Derive from state
    if STATE_FILE.is_file():
        try:
            state = json.loads(STATE_FILE.read_text(encoding="utf-8"))
            idx = state.get("last_analyzed_index", -1)
            modules = state.get("modules", [])
            if 0 <= idx < len(modules):
                mod_name = modules[idx]["name"].replace("/", "_").replace(" ", "_").lower()
                expected = REPORT_DIR / f"{today}_{mod_name}.md"
                if expected.is_file():
                    return expected
        except (json.JSONDecodeError, KeyError, OSError):
            pass

    # Fallback: newest .md for today
    try:
        candidates = sorted(
            REPORT_DIR.glob(f"{today}*.md"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if candidates:
            return candidates[0]
    except OSError:
        pass

    return None


def _git_commit_push(report: Path) -> bool:
    """Stage *report*, commit, and push to origin."""
    git = shutil.which("git")
    if git is None:
        print("GIT: git not found in PATH")
        return False

    # Path relative to repo root
    rel_path = str(report.relative_to(SCRIPT_DIR))

    def _git(args: list) -> bool:
        try:
            subprocess.run(
                [git, *args],
                cwd=str(SCRIPT_DIR),
                check=True,
                text=True,
                timeout=30,
            )
            return True
        except subprocess.CalledProcessError as exc:
            print(f"GIT: {' '.join(args)} failed — {exc}")
            return False
        except Exception as exc:
            print(f"GIT: {' '.join(args)} error — {exc}")
            return False

    if not _git(["add", rel_path]):
        return False

    commit_msg = f"Daily analysis report: {report.stem}"
    if not _git(["commit", "-m", commit_msg]):
        print("GIT: commit returned non-zero (may be nothing to commit)")

    if not _git(["push", "origin", "main"]):
        return False

    print(f"GIT: committed and pushed {rel_path} to origin/main")
    return True


# ---- Main ------------------------------------------------------------------
def main() -> int:
    tz = timezone(timedelta(hours=8))  # CST
    now_ts = datetime.now(tz).strftime("%Y%m%d_%H%M%S")
    log_file = LOG_DIR / f"analysis_{now_ts}.log"

    LOG_DIR.mkdir(parents=True, exist_ok=True)

    with open(log_file, "a", encoding="utf-8") as fh:
        # Redirect Python stdout/stderr to the log file
        sys.stdout = fh
        sys.stderr = fh

        print(f"=== Daily Analysis Started: {_now_str(tz)} ===")
        print(f"Project dir:  {PROJECT_DIR}")
        print(f"Python:       {sys.version}")
        print(f"Node version: {_sh_run([str(NODE_BIN_DIR / 'node'), '--version'])}")

        claude = shutil.which("claude", path=":".join([
            str(NODE_BIN_DIR), "/usr/local/bin", "/usr/bin", "/bin",
        ]))
        print(f"Claude path:  {claude or 'NOT FOUND'}")

        # Pre-flight checks
        if not PROMPT_FILE.is_file():
            print(f"FATAL: Prompt file not found: {PROMPT_FILE}")
            return 1
        if not PROJECT_DIR.is_dir():
            print(f"FATAL: Project dir not found: {PROJECT_DIR}")
            return 1
        if claude is None:
            print("FATAL: claude not found in PATH")
            return 1

        # Read prompt
        prompt = PROMPT_FILE.read_text(encoding="utf-8")
        print("Launching claude -p with analysis prompt...")
        print(f"Prompt length: {len(prompt)} chars")

        result = subprocess.run(
            [
                claude, "-p", prompt,
                "--permission-mode", "bypassPermissions",
                "--add-dir", str(PROJECT_DIR),
                "--add-dir", str(SCRIPT_DIR),
                "--no-session-persistence",
                "--model", "opus",
                "--verbose",
            ],
            cwd=str(PROJECT_DIR),
            stdout=fh,
            stderr=fh,
            env={
                **os.environ,
                "HOME": str(HOME),
                "PATH": ":".join([
                    str(NODE_BIN_DIR), "/usr/local/bin", "/usr/bin",
                    "/bin", "/usr/sbin", "/sbin",
                ]),
                "SHELL": "/bin/zsh",
                "LANG": "en_US.UTF-8",
            },
        )

        print(f"=== Daily Analysis Finished: {_now_str(tz)} (exit={result.returncode}) ===")

        # Commit and push the report
        report = _find_report(tz)
        if report:
            _git_commit_push(report)
        else:
            print("GIT: Could not locate today's report file — skipping commit")

    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
